spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://course-register-db.cy1qrgsd4zzq.us-east-1.rds.amazonaws.com:3306/test
    username: zhou
    password: 12345678
  jpa:
    hibernate.ddl-auto: create
    generate-ddl: true
    show-sql: true